// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wlanrwcolgitrirmdctn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndsYW5yd2NvbGdpdHJpcm1kY3RuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0ODE4NTcsImV4cCI6MjA3MjA1Nzg1N30.b0sAWyCLXxPnwO31Zjtq55GkdxWiU_LotqeNFJCKJ7o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});