import { 
  Loader2, 
  DollarSign, 
  TrendingUp, 
  TrendingDown, 
  Wallet, 
  CreditCard, 
  PieChart, 
  BarChart3, 
  Settings, 
  User, 
  LogOut, 
  Home, 
  Receipt, 
  Target, 
  Repeat, 
  Calendar, 
  Search, 
  Filter, 
  Download, 
  Upload, 
  Bell, 
  Moon, 
  Sun, 
  Menu,
  X,
  Plus,
  Minus,
  ArrowUpRight,
  ArrowDownRight,
  ArrowLeftRight,
  Eye,
  EyeOff,
  Edit,
  Trash2,
  MoreHorizontal,
  ChevronUp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  AlertCircle,
  CheckCircle,
  Info,
  Building2,
  Smartphone,
  Coins,
  Banknote,
  Calculator,
  Clock,
  MapPin,
  Mail,
  Phone,
  Shield,
  Lock,
  Unlock,
  FileText,
  Image,
  Camera,
  Mic,
  Speaker,
  Volume2,
  VolumeX,
  Wifi,
  WifiOff,
  Bluetooth,
  Battery,
  Zap,
  Star,
  Heart,
  ThumbsUp,
  ThumbsDown,
  Share,
  Copy,
  Link,
  ExternalLink,
  Bookmark,
  Flag,
  HelpCircle,
  Activity,
  Minus as TrendingFlat,
  Shuffle,
  RotateCcw,
  RotateCw,
  RefreshCw
} from 'lucide-react';

export const Icons = {
  spinner: Loader2,
  dollarSign: DollarSign,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  trendingFlat: TrendingFlat,
  wallet: Wallet,
  creditCard: CreditCard,
  pieChart: PieChart,
  barChart: BarChart3,
  settings: Settings,
  user: User,
  logout: LogOut,
  home: Home,
  receipt: Receipt,
  target: Target,
  repeat: Repeat,
  calendar: Calendar,
  search: Search,
  filter: Filter,
  download: Download,
  upload: Upload,
  bell: Bell,
  moon: Moon,
  sun: Sun,
  menu: Menu,
  close: X,
  plus: Plus,
  minus: Minus,
  arrowUpRight: ArrowUpRight,
  arrowDownRight: ArrowDownRight,
  arrowLeftRight: ArrowLeftRight,
  eye: Eye,
  eyeOff: EyeOff,
  edit: Edit,
  trash: Trash2,
  moreHorizontal: MoreHorizontal,
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  alertCircle: AlertCircle,
  checkCircle: CheckCircle,
  info: Info,
  building: Building2,
  smartphone: Smartphone,
  coins: Coins,
  banknote: Banknote,
  calculator: Calculator,
  clock: Clock,
  mapPin: MapPin,
  mail: Mail,
  phone: Phone,
  shield: Shield,
  lock: Lock,
  unlock: Unlock,
  fileText: FileText,
  image: Image,
  camera: Camera,
  mic: Mic,
  speaker: Speaker,
  volume: Volume2,
  volumeOff: VolumeX,
  wifi: Wifi,
  wifiOff: WifiOff,
  bluetooth: Bluetooth,
  battery: Battery,
  zap: Zap,
  star: Star,
  heart: Heart,
  thumbsUp: ThumbsUp,
  thumbsDown: ThumbsDown,
  share: Share,
  copy: Copy,
  link: Link,
  externalLink: ExternalLink,
  bookmark: Bookmark,
  flag: Flag,
  helpCircle: HelpCircle,
  activity: Activity,
  shuffle: Shuffle,
  rotateCcw: RotateCcw,
  rotateCw: RotateCw,
  refresh: RefreshCw,
};